export const PAGE_NAMES = {
    home: "Home",
    inventory: "Inventory",
    stock: "Stock",
    products: "Products",
    ledger: "Ledger",
    ledgerTransactions: "Transactions",
    ledgerManualEntry: "Manual Entry",
    purchases: "Purchases",
    makePurchase: "Make Purchase",
    suppliers: "Suppliers",
    orders: "Orders",
    staff: "Staff",
    clients: "Clients",
};
