export const PAGE_NAMES = {
    home: "Home",
    inventory: "Inventory",
    stock: "Stock",
    products: "Products",
    ledger: "Ledger",
    transactions: "Transactions",
    manualEntry: "Manual Entry",
    purchases: "Purchases",
    makePurchase: "Make Purchase",
    suppliers: "Suppliers",
    orders: "Orders",
    staff: "Staff",
    employees: "Employees",
    roles: "Roles",
    clients: "Clients",
    register: "Register",
    login: "Login",
};
