export const ROUTES = {
    home: "/",
    inventory: "/inventory",
    stock: "/inventory/stock",
    products: "/inventory/products",
    ledger: "/ledger",
    ledgerTransactions: "/ledger/transactions",
    ledgerManualEntry: "/ledger/manual-entry",
    purchases: "/purchases",
    makePurchase: "/purchases/make-purchase",
    suppliers: "/purchases/suppliers",
    orders: "/orders",
    staff: "/staff",
    clients: "/clients",
};
