export const ROUTES = {
    home: "/",
    inventory: "/inventory",
    stock: "/inventory/stock",
    products: "/inventory/products",
    ledger: "/ledger",
    transactions: "/ledger/transactions",
    manualEntry: "/ledger/manual-entry",
    purchases: "/purchases",
    makePurchase: "/purchases/make-purchase",
    suppliers: "/purchases/suppliers",
    orders: "/orders",
    staff: "/staff",
    employees: "/staff/employees",
    roles: "/staff/roles",
    clients: "/clients",
};
