interface InventoryItem {
    productName: string;
    batchNumber: string;
    currentQuantity: number;
    outgoingQuantity: number;
    dateStored: string;
    daysBeforeExpiry: number;
    supplier: string;
    price: number;
}

export const tableKeys = [
    "Product Name",
    "Batch Number",
    "Current Quantity",
    "Outgoing Quantity",
    "Date Stored",
    "Days Before Expiry",
    "Supplier",
    "Price",
];

export const data: InventoryItem[] = [
    {
        productName: "Pork Belly",
        batchNumber: "20260407a",
        currentQuantity: 50,
        outgoingQuantity: 23,
        dateStored: "2026-04-07",
        daysBeforeExpiry: 120,
        supplier: "Hello World Farms",
        price: 320,
    },
    {
        productName: "Pork Shoulder",
        batchNumber: "20260406b",
        currentQuantity: 75,
        outgoingQuantity: 30,
        dateStored: "2026-04-06",
        daysBeforeExpiry: 115,
        supplier: "Green Pastures Co.",
        price: 280,
    },
    {
        productName: "Pork Loin",
        batchNumber: "20260405c",
        currentQuantity: 40,
        outgoingQuantity: 12,
        dateStored: "2026-04-05",
        daysBeforeExpiry: 110,
        supplier: "Sunrise Meats",
        price: 350,
    },
    {
        productName: "Pork Ribs",
        batchNumber: "20260404d",
        currentQuantity: 60,
        outgoingQuantity: 20,
        dateStored: "2026-04-04",
        daysBeforeExpiry: 105,
        supplier: "Prime Cuts Ltd.",
        price: 300,
    },
    {
        productName: "Pork Ham",
        batchNumber: "20260403e",
        currentQuantity: 90,
        outgoingQuantity: 35,
        dateStored: "2026-04-03",
        daysBeforeExpiry: 130,
        supplier: "Farmhouse Meats",
        price: 260,
    },
    {
        productName: "Pork Tenderloin",
        batchNumber: "20260402f",
        currentQuantity: 30,
        outgoingQuantity: 10,
        dateStored: "2026-04-02",
        daysBeforeExpiry: 100,
        supplier: "Golden Fields",
        price: 400,
    },
    {
        productName: "Pork Jowl",
        batchNumber: "20260401g",
        currentQuantity: 25,
        outgoingQuantity: 8,
        dateStored: "2026-04-01",
        daysBeforeExpiry: 95,
        supplier: "Rustic Farms",
        price: 270,
    },
    {
        productName: "Pork Hock",
        batchNumber: "20260331h",
        currentQuantity: 55,
        outgoingQuantity: 18,
        dateStored: "2026-03-31",
        daysBeforeExpiry: 90,
        supplier: "Heritage Pork Co.",
        price: 240,
    },
    {
        productName: "Pork Fatback",
        batchNumber: "20260330i",
        currentQuantity: 70,
        outgoingQuantity: 22,
        dateStored: "2026-03-30",
        daysBeforeExpiry: 140,
        supplier: "Valley Farms",
        price: 200,
    },
    {
        productName: "Pork Leg",
        batchNumber: "20260329j",
        currentQuantity: 80,
        outgoingQuantity: 28,
        dateStored: "2026-03-29",
        daysBeforeExpiry: 125,
        supplier: "Fresh Harvest Meats",
        price: 290,
    },
    {
        productName: "Pork Belly",
        batchNumber: "20260408k",
        currentQuantity: 45,
        outgoingQuantity: 15,
        dateStored: "2026-04-08",
        daysBeforeExpiry: 118,
        supplier: "Hello World Farms",
        price: 325,
    },
    {
        productName: "Pork Belly",
        batchNumber: "20260409l",
        currentQuantity: 60,
        outgoingQuantity: 25,
        dateStored: "2026-04-09",
        daysBeforeExpiry: 119,
        supplier: "Green Pastures Co.",
        price: 330,
    },
    {
        productName: "Pork Shoulder",
        batchNumber: "20260408m",
        currentQuantity: 80,
        outgoingQuantity: 35,
        dateStored: "2026-04-08",
        daysBeforeExpiry: 112,
        supplier: "Sunrise Meats",
        price: 285,
    },
    {
        productName: "Pork Ribs",
        batchNumber: "20260407n",
        currentQuantity: 55,
        outgoingQuantity: 18,
        dateStored: "2026-04-07",
        daysBeforeExpiry: 102,
        supplier: "Prime Cuts Ltd.",
        price: 305,
    },
    {
        productName: "Pork Loin",
        batchNumber: "20260406o",
        currentQuantity: 38,
        outgoingQuantity: 14,
        dateStored: "2026-04-06",
        daysBeforeExpiry: 108,
        supplier: "Farmhouse Meats",
        price: 355,
    }
];